# Generated by Django 5.2.7 on 2025-11-03 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_caption',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='photo_tag',
            name='photo_id',
        ),
        migrations.AlterField(
            model_name='caption',
            name='caption',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photo_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='caption',
            unique_together={('user', 'caption')},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_path_id', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('is_tagged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo_caption',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='photo_tag',
            name='photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
    ]
