# Generated by Django 5.2.7 on 2025-10-23 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_tag',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='embedding',
        ),
        migrations.AddField(
            model_name='photo_tag',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
