# Generated by Django 5.2.7 on 2025-10-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_rename_caption_tag_photo_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo_caption',
            old_name='ct_id',
            new_name='pc_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='embedding',
        ),
        migrations.DeleteModel(
            name='RepVec_Tag',
        ),
    ]
