# Generated by Django 5.2.7 on 2025-10-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_rename_ct_id_photo_caption_pc_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepVec_Tag',
        ),
    ]
