# Generated by Django 5.2.7 on 2025-10-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_rename_ct_id_photo_caption_pc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_caption',
            name='caption_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.caption'),
        ),
        migrations.AlterField(
            model_name='photo_caption',
            name='photo_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='photo_tag',
            name='photo_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='photo_tag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.tag'),
        ),
    ]
