# Generated by Django 5.2.7 on 2025-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_photo_caption_caption_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_caption',
            name='caption_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='photo_caption',
            name='photo_id',
            field=models.UUIDField(unique=True),
        ),
    ]
