# Generated by Django 5.2.7 on 2025-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_photo_caption_caption_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo_caption',
            old_name='caption_id',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='photo_caption',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
