# Generated by Django 5.2.7 on 2025-10-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_photo_caption_caption_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_tag',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='photo_tag',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.tag'),
        ),
        migrations.AlterField(
            model_name='photo_tag',
            name='photo_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
