# Generated by Django 5.2.7 on 2025-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_photo_tag_tag_id_photo_tag_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_tag',
            name='photo_id',
            field=models.UUIDField(),
        ),
    ]
