# Generated by Django 5.2.7 on 2025-10-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_remove_photo_tag_tag_id_photo_tag_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_caption',
            name='caption_id',
        ),
        migrations.AddField(
            model_name='photo_caption',
            name='caption',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.caption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo_caption',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo_caption',
            name='photo_id',
            field=models.UUIDField(),
        ),
    ]
