# Generated by Django 5.2.7 on 2025-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_remove_photo_caption_caption_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_tag',
            name='photo_id',
            field=models.UUIDField(),
        ),
    ]
